{% set name = 'cacao' %}
{% set version = os.environ.get('TRAVIS_TAG', '').replace('v.', '').replace('v', '') or 'dev' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  rpaths:
    - lib/
    - lib/R/library/

requirements:
  build:
    - python =3.7
    - r-base =4.0.2
    - curl
    - unzip
    - tar
    - toml
    - pip
    - setuptools
    #
    ### Need R modules to install the cacao R package during build-time
    - r-devtools
    - r-rmarkdown
    - r-configr
    - r-dplyr
    - r-stringr
    - r-tidyr
    - r-magrittr
    - r-htmltools
    - r-plotly
    - r-ggplot2
    - r-dt
    - r-summarywidget
    - r-rlogging
    - r-crosstalk
    - r-forcats

  run:
    - python =3.7
    - r-base =4.0.2
    - bedtools
    - htslib
    - numpy
    - cython
    - scipy
    - pandas
    - cyvcf2
    - toml
    - samtools
    - mosdepth
    - tabix
    - pandoc
    - r-rmarkdown
    - r-configr
    - r-dplyr
    - r-stringr
    - r-tidyr
    - r-magrittr
    - r-htmltools
    - r-plotly
    - r-ggplot2
    - r-dt
    - r-summarywidget
    - r-rlogging
    - r-crosstalk
    - r-forcats

test:
  commands:
    - cacao_wflow.py --version
    - cacao.py --help
    - '$R -e "library(cacao)"'

about:
  home: https://github.com/sigven/cacao
  license: MIT
  summary: Callable Cancer Loci - assessment of sequencing coverage for actionable and pathogenic loci in cancer

