{% set name = 'cacao_dockerized' %}
{% set version = os.environ.get('TRAVIS_TAG', '').replace('v.', '').replace('v', '') or 'dev' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python
    - toml
  run:
    - python
    - toml

test:
  commands:
    - cacao_wflow.py --version

about:
  home: https://github.com/sigven/cacao
  license: MIT
  summary: Callable Cancer Loci - assessment of sequencing coverage for actionable and pathogenic loci in cancer

